# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.105.1-26.2
maven_group=com.jeff.pets.cobblepets

# Dependencies
geckolibVersion=5.5.1
fabric_api_version=0.153.0+26.2
modmenu_version=20.0.0-beta.4
yacl_version=3.9.4+26.2-fabric
petsmod_version=0.7.10-26.2
cloth_config_version=26.2.155