package com.jeff.pets.cobblepets.client;

import com.jeff.pets.Central;
import com.jeff.pets.PetsClientInitializer;
import com.jeff.pets.Utils;
import com.jeff.pets.cobblepets.Cobblepets;
import com.jeff.pets.cobblepets.client.rendering.gen1.abra_tree.abra.AbraRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.abra_tree.alakazam.AlakazamRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.abra_tree.kadabra.KadabraRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.bellsprout_tree.bellsprout.BellsproutRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.bellsprout_tree.victreebel.VictreebelRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.bellsprout_tree.weepinbell.WeepinbellRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.bulbasaur_tree.bulbasaur.BulbasaurRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.bulbasaur_tree.ivysaur.IvysaurRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.bulbasaur_tree.venusaur.VenusaurRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.clefairy_tree.clefable.ClefableRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.clefairy_tree.clefairy.ClefairyRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.caterpie_tree.butterfree.ButterfreeRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.caterpie_tree.caterpie.CaterpieRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.caterpie_tree.metapod.MetapodRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.charmander_tree.charizard.CharizardRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.charmander_tree.charmander.CharmanderRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.charmander_tree.charmeleon.CharmeleonRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.diglett_tree.diglett.DiglettRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.diglett_tree.dugtrio.DugtrioRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.ditto.DittoRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.doduo_tree.dodrio.DodrioRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.doduo_tree.doduo.DoduoRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.drowzee_tree.drowzee.DrowzeeRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.drowzee_tree.hypno.HypnoRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.ekans_tree.arbok.ArbokRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.ekans_tree.ekans.EkansRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.exeggcute_tree.exeggcute.ExeggcuteRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.exeggcute_tree.exeggutor.ExeggutorRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.farfetchd.FarfetchdRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.gastly_tree.gastly.GastlyRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.gastly_tree.gengar.GengarRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.gastly_tree.haunter.HaunterRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.geodude_tree.geodude.GeodudeRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.geodude_tree.golem.GolemRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.geodude_tree.graveler.GravelerRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.grimer_tree.grimer.GrimerRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.grimer_tree.muk.MukRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.growlith_tree.arcanine.ArcanineRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.growlith_tree.growlith.GrowlithRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.jigglypuff_tree.jigglypuff.JigglypuffRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.jigglypuff_tree.wigglytuff.WigglytuffRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.krabby_tree.kingler.KinglerRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.krabby_tree.krabby.KrabbyRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.machop_tree.machamp.MachampRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.machop_tree.machoke.MachokeRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.machop_tree.machop.MachopRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.magnemite_tree.magnemite.MagnemiteRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.magnemite_tree.magneton.MagnetonRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.mankey_tree.mankey.MankeyRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.mankey_tree.primeape.PrimeapeRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.meowth_tree.meowth.MeowthRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.meowth_tree.persian.PersianRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.mew_tree.mew.MewRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.mew_tree.mewtwo.MewtwoRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.nidoranf_tree.nidoqueen.NidoqueenRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.nidoranf_tree.nidoranf.NidoranfRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.nidoranf_tree.nidorina.NidorinaRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.nidoranm_tree.nidoking.NidokingRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.nidoranm_tree.nidoranm.NidoranmRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.nidoranm_tree.nidorino.NidorinoRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.oddish_tree.gloom.GloomRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.oddish_tree.oddish.OddishRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.oddish_tree.vileplume.VileplumeRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.onix_tree.onix.OnixRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.paras_tree.paras.ParasRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.paras_tree.parasect.ParasectRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.pidgey_tree.pidgeot.PidgeotRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.pidgey_tree.pidgeotto.PidgeottoRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.pidgey_tree.pidgey.PidgeyRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.pikachu_tree.pikachu.PikachuRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.pikachu_tree.raichu.RaichuRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.poliwag_tree.poliwag.PoliwagRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.poliwag_tree.poliwhirl.PoliwhirlRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.poliwag_tree.poliwrath.PoliwrathRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.ponyta_tree.ponyta.PonytaRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.ponyta_tree.rapidash.RapidashRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.psyduck_tree.golduck.GolduckRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.psyduck_tree.psyduck.PsyduckRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.rattata_tree.raticate.RaticateRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.rattata_tree.rattata.RattataRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.sandshrew_tree.sandshrew.SandshrewRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.sandshrew_tree.sandslash.SandslashRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.seel_tree.dewgong.DewgongRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.seel_tree.seel.SeelRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.shellder_tree.cloyster.CloysterRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.shellder_tree.shellder.ShellderRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.slowpoke_tree.slowbro.SlowbroRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.slowpoke_tree.slowpoke.SlowpokeRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.spearow_tree.fearow.FearowRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.spearow_tree.spearow.SpearowRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.squirtle_tree.blastoise.BlastoiseRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.squirtle_tree.squirtle.SquirtleRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.squirtle_tree.wartortle.WartortleRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.tentacool_tree.tentacool.TentacoolRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.tentacool_tree.tentacruel.TentacruelRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.venonat_tree.venomoth.VenomothRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.venonat_tree.venonat.VenonatRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.voltorb_tree.electrode.ElectrodeRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.voltorb_tree.voltorb.VoltorbRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.vulpix_tree.ninetales.NinetalesRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.vulpix_tree.vulpix.VulpixRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.weedle_tree.beedrill.BeedrillRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.weedle_tree.kakuna.KakunaRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.weedle_tree.weedle.WeedleRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.zubat_tree.golbat.GolbatRenderer;
import com.jeff.pets.cobblepets.client.rendering.gen1.zubat_tree.zubat.ZubatRenderer;
import me.shedaniel.autoconfig.AutoConfig;
import me.shedaniel.autoconfig.serializer.GsonConfigSerializer;
import net.fabricmc.api.ClientModInitializer;
import net.minecraft.world.entity.ai.goal.CatLieOnBedGoal;

import java.util.Arrays;

import static com.jeff.pets.cobblepets.Cobblepets.*;
import static com.jeff.pets.cobblepets.Cobblepets.MOD_ID;
import static net.minecraft.client.renderer.entity.EntityRenderers.register;

public class CobblepetsClient implements ClientModInitializer {
    public static CobblepetsConfig COBBLE_CONFIG;

    @Override
    public void onInitializeClient() {

        PetsClientInitializer.ADDONS.add(MOD_ID);

        this.addAllToPetList(Vals.getVals());
        this.setUpConfig();
        this.checkForNullObjects();
        this.setUpRendering();
    }

    private void setUpConfig() {
        AutoConfig.register(CobblepetsConfig.class, GsonConfigSerializer::new);
        COBBLE_CONFIG = AutoConfig.getConfigHolder(CobblepetsConfig.class).getConfig();
    }

    private void checkForNullObjects() {
        COBBLE_CONFIG.bulbasorName = Utils.checkNullString(COBBLE_CONFIG.bulbasorName);
        COBBLE_CONFIG.ivysaurName = Utils.checkNullString(COBBLE_CONFIG.ivysaurName);
        COBBLE_CONFIG.venusaurName = Utils.checkNullString(COBBLE_CONFIG.venusaurName);
        COBBLE_CONFIG.charmanderName = Utils.checkNullString(COBBLE_CONFIG.charmanderName);
        COBBLE_CONFIG.charmeleonName = Utils.checkNullString(COBBLE_CONFIG.charmeleonName);
        COBBLE_CONFIG.charizardName = Utils.checkNullString(COBBLE_CONFIG.charizardName);
        COBBLE_CONFIG.squirtleName = Utils.checkNullString(COBBLE_CONFIG.squirtleName);
        COBBLE_CONFIG.wartortleName = Utils.checkNullString(COBBLE_CONFIG.wartortleName);
        COBBLE_CONFIG.blastoiseName = Utils.checkNullString(COBBLE_CONFIG.blastoiseName);
        COBBLE_CONFIG.caterpieName = Utils.checkNullString(COBBLE_CONFIG.caterpieName);
        COBBLE_CONFIG.metapodName = Utils.checkNullString(COBBLE_CONFIG.metapodName);
        COBBLE_CONFIG.butterfreeName = Utils.checkNullString(COBBLE_CONFIG.butterfreeName);
        COBBLE_CONFIG.butterfreeSkin = Utils.checkNullString(COBBLE_CONFIG.butterfreeSkin, "normal");
        COBBLE_CONFIG.weedleName = Utils.checkNullString(COBBLE_CONFIG.weedleName);
        COBBLE_CONFIG.kakunaName = Utils.checkNullString(COBBLE_CONFIG.kakunaName);
        COBBLE_CONFIG.beedrillName = Utils.checkNullString(COBBLE_CONFIG.beedrillName);
        COBBLE_CONFIG.pidgeyName = Utils.checkNullString(COBBLE_CONFIG.pidgeyName);
        COBBLE_CONFIG.pidgeottoName = Utils.checkNullString(COBBLE_CONFIG.pidgeottoName);
        COBBLE_CONFIG.pidgeotName = Utils.checkNullString(COBBLE_CONFIG.pidgeotName);
        COBBLE_CONFIG.mewName = Utils.checkNullString(COBBLE_CONFIG.mewName);
        COBBLE_CONFIG.mewtwoName = Utils.checkNullString(COBBLE_CONFIG.mewtwoName);
        COBBLE_CONFIG.dittoName = Utils.checkNullString(COBBLE_CONFIG.dittoName);
        COBBLE_CONFIG.rattataName = Utils.checkNullString(COBBLE_CONFIG.rattataName);
        COBBLE_CONFIG.raticateName = Utils.checkNullString(COBBLE_CONFIG.raticateName);
        COBBLE_CONFIG.spearowName = Utils.checkNullString(COBBLE_CONFIG.spearowName);
        COBBLE_CONFIG.fearowName = Utils.checkNullString(COBBLE_CONFIG.spearowName);
        COBBLE_CONFIG.ekansName = Utils.checkNullString(COBBLE_CONFIG.ekansName);
        COBBLE_CONFIG.arbokName = Utils.checkNullString(COBBLE_CONFIG.arbokName);
        COBBLE_CONFIG.pikachuName = Utils.checkNullString(COBBLE_CONFIG.pikachuName);
        COBBLE_CONFIG.raichuName = Utils.checkNullString(COBBLE_CONFIG.raichuName);
        COBBLE_CONFIG.sandshrewName = Utils.checkNullString(COBBLE_CONFIG.sandshrewName);
        COBBLE_CONFIG.sandslashName = Utils.checkNullString(COBBLE_CONFIG.sandslashName);
        COBBLE_CONFIG.nidoranfName = Utils.checkNullString(COBBLE_CONFIG.nidoranfName);
        COBBLE_CONFIG.nidorinaName = Utils.checkNullString(COBBLE_CONFIG.nidorinaName);
        COBBLE_CONFIG.nidoqueenName = Utils.checkNullString(COBBLE_CONFIG.nidoqueenName);
        COBBLE_CONFIG.nidoranmName = Utils.checkNullString(COBBLE_CONFIG.nidoranmName);
        COBBLE_CONFIG.nidorinoName = Utils.checkNullString(COBBLE_CONFIG.nidorinoName);
        COBBLE_CONFIG.nidokingName = Utils.checkNullString(COBBLE_CONFIG.nidokingName);
        COBBLE_CONFIG.clefairyName = Utils.checkNullString(COBBLE_CONFIG.clefairyName);
        COBBLE_CONFIG.clefableName = Utils.checkNullString(COBBLE_CONFIG.clefableName);
        COBBLE_CONFIG.vulpixName = Utils.checkNullString(COBBLE_CONFIG.vulpixName);
        COBBLE_CONFIG.ninetalesName = Utils.checkNullString(COBBLE_CONFIG.ninetalesName);
        COBBLE_CONFIG.jigglypuffName = Utils.checkNullString(COBBLE_CONFIG.jigglypuffName);
        COBBLE_CONFIG.wigglytuffName = Utils.checkNullString(COBBLE_CONFIG.wigglytuffName);
        COBBLE_CONFIG.zubatName = Utils.checkNullString(COBBLE_CONFIG.zubatName);
        COBBLE_CONFIG.golbatName = Utils.checkNullString(COBBLE_CONFIG.golbatName);
        COBBLE_CONFIG.oddishName = Utils.checkNullString(COBBLE_CONFIG.oddishName);
        COBBLE_CONFIG.gloomName = Utils.checkNullString(COBBLE_CONFIG.gloomName);
        COBBLE_CONFIG.gloomSkin = Utils.checkNullString(COBBLE_CONFIG.gloomSkin, "normal");
        COBBLE_CONFIG.vileplumeName = Utils.checkNullString(COBBLE_CONFIG.vileplumeName);
        COBBLE_CONFIG.vileplumeSkin = Utils.checkNullString(COBBLE_CONFIG.vileplumeSkin, "normal");
        COBBLE_CONFIG.parasName = Utils.checkNullString(COBBLE_CONFIG.parasName);
        COBBLE_CONFIG.parasectName = Utils.checkNullString(COBBLE_CONFIG.parasectName);
        COBBLE_CONFIG.venonatName = Utils.checkNullString(COBBLE_CONFIG.venonatName);
        COBBLE_CONFIG.venomothName = Utils.checkNullString(COBBLE_CONFIG.venomothName);
        COBBLE_CONFIG.diglettName = Utils.checkNullString(COBBLE_CONFIG.diglettName);
        COBBLE_CONFIG.diglettSkin = Utils.checkNullString(COBBLE_CONFIG.diglettSkin, "normal");
        COBBLE_CONFIG.dugtrioName = Utils.checkNullString(COBBLE_CONFIG.dugtrioName);
        COBBLE_CONFIG.dugtrioSkin = Utils.checkNullString(COBBLE_CONFIG.dugtrioSkin, "normal");
        COBBLE_CONFIG.meowthName = Utils.checkNullString(COBBLE_CONFIG.meowthName);
        COBBLE_CONFIG.meowthSkin = Utils.checkNullString(COBBLE_CONFIG.meowthSkin, "normal");
        COBBLE_CONFIG.persianName = Utils.checkNullString(COBBLE_CONFIG.persianName);
        COBBLE_CONFIG.persianSkin = Utils.checkNullString(COBBLE_CONFIG.persianSkin, "normal");
        COBBLE_CONFIG.psyduckName = Utils.checkNullString(COBBLE_CONFIG.psyduckName);
        COBBLE_CONFIG.golduckName = Utils.checkNullString(COBBLE_CONFIG.golduckName);
        COBBLE_CONFIG.mankeyName = Utils.checkNullString(COBBLE_CONFIG.mankeyName);
        COBBLE_CONFIG.primeapeName = Utils.checkNullString(COBBLE_CONFIG.primeapeName);
        COBBLE_CONFIG.growlithName = Utils.checkNullString(COBBLE_CONFIG.growlithName);
        COBBLE_CONFIG.arcanineName = Utils.checkNullString(COBBLE_CONFIG.arcanineName);
        COBBLE_CONFIG.poliwagName = Utils.checkNullString(COBBLE_CONFIG.poliwagName);
        COBBLE_CONFIG.poliwhirlName = Utils.checkNullString(COBBLE_CONFIG.poliwhirlName);
        COBBLE_CONFIG.poliwrathName = Utils.checkNullString(COBBLE_CONFIG.poliwrathName);
        COBBLE_CONFIG.abraName = Utils.checkNullString(COBBLE_CONFIG.abraName);
        COBBLE_CONFIG.kadabraName = Utils.checkNullString(COBBLE_CONFIG.kadabraName);
        COBBLE_CONFIG.alakazamName = Utils.checkNullString(COBBLE_CONFIG.alakazamName);
        COBBLE_CONFIG.machopName = Utils.checkNullString(COBBLE_CONFIG.machopName);
        COBBLE_CONFIG.machokeName = Utils.checkNullString(COBBLE_CONFIG.machokeName);
        COBBLE_CONFIG.machampName = Utils.checkNullString(COBBLE_CONFIG.machampName);
        COBBLE_CONFIG.bellsproutName = Utils.checkNullString(COBBLE_CONFIG.bellsproutName);
        COBBLE_CONFIG.weepinbellName = Utils.checkNullString(COBBLE_CONFIG.weepinbellName);
        COBBLE_CONFIG.victreebelName = Utils.checkNullString(COBBLE_CONFIG.victreebelName);
        COBBLE_CONFIG.tentacoolName = Utils.checkNullString(COBBLE_CONFIG.tentacoolName);
        COBBLE_CONFIG.tentacruelName = Utils.checkNullString(COBBLE_CONFIG.tentacruelName);
        COBBLE_CONFIG.geodudeName = Utils.checkNullString(COBBLE_CONFIG.geodudeName);
        COBBLE_CONFIG.geodudeSkin = Utils.checkNullString(COBBLE_CONFIG.geodudeSkin, "normal");
        COBBLE_CONFIG.gravelerName = Utils.checkNullString(COBBLE_CONFIG.gravelerName);
        COBBLE_CONFIG.gravelerSkin = Utils.checkNullString(COBBLE_CONFIG.gravelerSkin, "normal");
        COBBLE_CONFIG.golemName = Utils.checkNullString(COBBLE_CONFIG.golemName);
        COBBLE_CONFIG.golemSkin = Utils.checkNullString(COBBLE_CONFIG.golemSkin, "normal");
        COBBLE_CONFIG.ponytaName = Utils.checkNullString(COBBLE_CONFIG.ponytaName);
        COBBLE_CONFIG.ponytaSkin = Utils.checkNullString(COBBLE_CONFIG.ponytaSkin, "normal");
        COBBLE_CONFIG.rapidashName = Utils.checkNullString(COBBLE_CONFIG.rapidashName);
        COBBLE_CONFIG.rapidashSkin = Utils.checkNullString(COBBLE_CONFIG.rapidashSkin, "normal");
        COBBLE_CONFIG.slowbroName = Utils.checkNullString(COBBLE_CONFIG.slowbroName);
        COBBLE_CONFIG.slowbroSkin = Utils.checkNullString(COBBLE_CONFIG.slowbroSkin, "normal");
        COBBLE_CONFIG.slowpokeName = Utils.checkNullString(COBBLE_CONFIG.slowpokeName);
        COBBLE_CONFIG.slowpokeSkin = Utils.checkNullString(COBBLE_CONFIG.slowpokeSkin, "normal");
        COBBLE_CONFIG.magnemiteName = Utils.checkNullString(COBBLE_CONFIG.magnemiteName);
        COBBLE_CONFIG.magnetonName = Utils.checkNullString(COBBLE_CONFIG.magnetonName);
        COBBLE_CONFIG.farfetchdName = Utils.checkNullString(COBBLE_CONFIG.farfetchdName);
        COBBLE_CONFIG.farfetchdSkin = Utils.checkNullString(COBBLE_CONFIG.farfetchdSkin, "normal");
        COBBLE_CONFIG.doduoName = Utils.checkNullString(COBBLE_CONFIG.doduoName);
        COBBLE_CONFIG.dodrioName = Utils.checkNullString(COBBLE_CONFIG.dodrioName);
        COBBLE_CONFIG.seelName = Utils.checkNullString(COBBLE_CONFIG.seelName);
        COBBLE_CONFIG.dewgongName = Utils.checkNullString(COBBLE_CONFIG.dewgongName);
        COBBLE_CONFIG.grimerName = Utils.checkNullString(COBBLE_CONFIG.grimerName);
        COBBLE_CONFIG.grimerSkin = Utils.checkNullString(COBBLE_CONFIG.grimerSkin, "normal");
        COBBLE_CONFIG.mukName = Utils.checkNullString(COBBLE_CONFIG.mukName);
        COBBLE_CONFIG.mukSkin = Utils.checkNullString(COBBLE_CONFIG.mukSkin, "normal");
        COBBLE_CONFIG.shellderName = Utils.checkNullString(COBBLE_CONFIG.shellderName);
        COBBLE_CONFIG.cloysterName = Utils.checkNullString(COBBLE_CONFIG.cloysterName);
        COBBLE_CONFIG.gastlyName = Utils.checkNullString(COBBLE_CONFIG.gastlyName);
        COBBLE_CONFIG.haunterName = Utils.checkNullString(COBBLE_CONFIG.haunterName);
        COBBLE_CONFIG.gengarName = Utils.checkNullString(COBBLE_CONFIG.gengarName);
        COBBLE_CONFIG.onixName = Utils.checkNullString(COBBLE_CONFIG.onixName);
        COBBLE_CONFIG.drowzeeName = Utils.checkNullString(COBBLE_CONFIG.drowzeeName);
        COBBLE_CONFIG.hypnoName = Utils.checkNullString(COBBLE_CONFIG.hypnoName);
        COBBLE_CONFIG.krabbyName = Utils.checkNullString(COBBLE_CONFIG.krabbyName);
        COBBLE_CONFIG.kinglerName = Utils.checkNullString(COBBLE_CONFIG.kinglerName);
        COBBLE_CONFIG.voltorbName = Utils.checkNullString(COBBLE_CONFIG.voltorbName);
        COBBLE_CONFIG.voltorbSkin = Utils.checkNullString(COBBLE_CONFIG.voltorbSkin, "normal");
        COBBLE_CONFIG.electrodeName = Utils.checkNullString(COBBLE_CONFIG.electrodeName);
        COBBLE_CONFIG.electrodeSkin = Utils.checkNullString(COBBLE_CONFIG.electrodeSkin, "normal");
        COBBLE_CONFIG.exeggcuteName = Utils.checkNullString(COBBLE_CONFIG.exeggcuteName);
        COBBLE_CONFIG.exeggcuteSkin = Utils.checkNullString(COBBLE_CONFIG.exeggcuteSkin, "normal");
        COBBLE_CONFIG.exeggutorName = Utils.checkNullString(COBBLE_CONFIG.exeggutorName);
        COBBLE_CONFIG.exeggutorSkin = Utils.checkNullString(COBBLE_CONFIG.exeggutorSkin, "normal");

        AutoConfig.getConfigHolder(CobblepetsConfig.class).save();
    }

    private void setUpRendering() {
        register(BULBASAUR, BulbasaurRenderer::new);
        register(IVYSAUR, IvysaurRenderer::new);
        register(VENUSAUR, VenusaurRenderer::new);
        register(CHARMANDER, CharmanderRenderer::new);
        register(CHARMELEON, CharmeleonRenderer::new);
        register(CHARIZARD, CharizardRenderer::new);
        register(SQUIRTLE, SquirtleRenderer::new);
        register(WARTORTLE, WartortleRenderer::new);
        register(BLASTOISE, BlastoiseRenderer::new);
        register(CATERPIE, CaterpieRenderer::new);
        register(METAPOD, MetapodRenderer::new);
        register(BUTTERFREE, ButterfreeRenderer::new);
        register(WEEDLE, WeedleRenderer::new);
        register(KAKUNA, KakunaRenderer::new);
        register(BEEDRILL, BeedrillRenderer::new);
        register(PIDGEY, PidgeyRenderer::new);
        register(PIDGEOTTO, PidgeottoRenderer::new);
        register(PIDGEOT, PidgeotRenderer::new);
        register(MEW, MewRenderer::new);
        register(MEWTWO, MewtwoRenderer::new);
        register(DITTO, DittoRenderer::new);
        register(RATTATA, RattataRenderer::new);
        register(RATICATE, RaticateRenderer::new);
        register(SPEAROW, SpearowRenderer::new);
        register(FEAROW, FearowRenderer::new);
        register(EKANS, EkansRenderer::new);
        register(ARBOK, ArbokRenderer::new);
        register(PIKACHU, PikachuRenderer::new);
        register(RAICHU, RaichuRenderer::new);
        register(SANDSHREW, SandshrewRenderer::new);
        register(SANDSLASH, SandslashRenderer::new);
        register(NIDORANF, NidoranfRenderer::new);
        register(NIDORINA, NidorinaRenderer::new);
        register(NIDOQUEEN, NidoqueenRenderer::new);
        register(NIDORANM, NidoranmRenderer::new);
        register(NIDORINO, NidorinoRenderer::new);
        register(NIDOKING, NidokingRenderer::new);
        register(CLEFAIRY, ClefairyRenderer::new);
        register(CLEFABLE, ClefableRenderer::new);
        register(VULPIX, VulpixRenderer::new);
        register(NINETALES, NinetalesRenderer::new);
        register(JIGGLYPUFF, JigglypuffRenderer::new);
        register(WIGGLYTUFF, WigglytuffRenderer::new);
        register(ZUBAT, ZubatRenderer::new);
        register(GOLBAT, GolbatRenderer::new);
        register(ODDISH, OddishRenderer::new);
        register(GLOOM, GloomRenderer::new);
        register(VILEPLUME, VileplumeRenderer::new);
        register(PARAS, ParasRenderer::new);
        register(PARASECT, ParasectRenderer::new);
        register(VENONAT, VenonatRenderer::new);
        register(VENOMOTH, VenomothRenderer::new);
        register(DIGLETT, DiglettRenderer::new);
        register(DUGTRIO, DugtrioRenderer::new);
        register(MEOWTH, MeowthRenderer::new);
        register(PERSIAN, PersianRenderer::new);
        register(PSYDUCK, PsyduckRenderer::new);
        register(GOLDUCK, GolduckRenderer::new);
        register(MANKEY, MankeyRenderer::new);
        register(PRIMEAPE, PrimeapeRenderer::new);
        register(GROWLITHE, GrowlithRenderer::new);
        register(ARCANINE, ArcanineRenderer::new);
        register(POLIWAG, PoliwagRenderer::new);
        register(POLIWHIRL, PoliwhirlRenderer::new);
        register(POLIWRATH, PoliwrathRenderer::new);
        register(ABRA, AbraRenderer::new);
        register(KADABRA, KadabraRenderer::new);
        register(ALAKAZAM, AlakazamRenderer::new);
        register(MACHOP, MachopRenderer::new);
        register(MACHOKE, MachokeRenderer::new);
        register(MACHAMP, MachampRenderer::new);
        register(BELLSPROUT, BellsproutRenderer::new);
        register(WEEPINBELL, WeepinbellRenderer::new);
        register(VICTREEBEL, VictreebelRenderer::new);
        register(TENTACOOL, TentacoolRenderer::new);
        register(TENTACRUEL, TentacruelRenderer::new);
        register(GEODUDE, GeodudeRenderer::new);
        register(GRAVELER, GravelerRenderer::new);
        register(GOLEM, GolemRenderer::new);
        register(PONYTA, PonytaRenderer::new);
        register(RAPIDASH, RapidashRenderer::new);
        register(SLOWPOKE, SlowpokeRenderer::new);
        register(SLOWBRO, SlowbroRenderer::new);
        register(MAGNEMITE, MagnemiteRenderer::new);
        register(MAGNETON, MagnetonRenderer::new);
        register(FARFETCHD, FarfetchdRenderer::new);
        register(DODUO, DoduoRenderer::new);
        register(DODRIO, DodrioRenderer::new);
        register(SEEL, SeelRenderer::new);
        register(DEWGONG, DewgongRenderer::new);
        register(GRIMER, GrimerRenderer::new);
        register(MUK, MukRenderer::new);
        register(SHELLDER, ShellderRenderer::new);
        register(CLOYSTER, CloysterRenderer::new);
        register(GASTLY, GastlyRenderer::new);
        register(HAUNTER, HaunterRenderer::new);
        register(GENGAR, GengarRenderer::new);
        register(ONIX, OnixRenderer::new);
        register(DROWZEE, DrowzeeRenderer::new);
        register(HYPNO, HypnoRenderer::new);
        register(KRABBY, KrabbyRenderer::new);
        register(KINGLER, KinglerRenderer::new);
        register(VOLTORB, VoltorbRenderer::new);
        register(ELECTRODE, ElectrodeRenderer::new);
        register(EXEGGCUTE, ExeggcuteRenderer::new);
        register(EXEGGUTOR, ExeggutorRenderer::new);
    }

    private void addAllToPetList(String ... s) {
        Central.PETS_LIST.addAll(Arrays.asList(s));
    }
}