package com.jeff.pets.cobblepets.client.mixin;

import com.jeff.pets.client.Utils;
import com.jeff.pets.cobblepets.Cobblepets;
import com.jeff.pets.cobblepets.pets.gen1.abra.Abra;
import com.jeff.pets.cobblepets.pets.gen1.abra.Alakazam;
import com.jeff.pets.cobblepets.pets.gen1.abra.Kadabra;
import com.jeff.pets.cobblepets.pets.gen1.bellsprout.Bellsprout;
import com.jeff.pets.cobblepets.pets.gen1.bellsprout.Victreebel;
import com.jeff.pets.cobblepets.pets.gen1.bellsprout.Weepinbell;
import com.jeff.pets.cobblepets.pets.gen1.bulbasaur.Bulbasaur;
import com.jeff.pets.cobblepets.pets.gen1.bulbasaur.Ivysaur;
import com.jeff.pets.cobblepets.pets.gen1.bulbasaur.Venusaur;
import com.jeff.pets.cobblepets.pets.gen1.charmander.Charizard;
import com.jeff.pets.cobblepets.pets.gen1.charmander.Charmander;
import com.jeff.pets.cobblepets.pets.gen1.charmander.Charmeleon;
import com.jeff.pets.cobblepets.pets.gen1.clefairy.Clefable;
import com.jeff.pets.cobblepets.pets.gen1.clefairy.Clefairy;
import com.jeff.pets.cobblepets.pets.gen1.cubone.Cubone;
import com.jeff.pets.cobblepets.pets.gen1.cubone.Marowak;
import com.jeff.pets.cobblepets.pets.gen1.diglett.Diglett;
import com.jeff.pets.cobblepets.pets.gen1.diglett.Dugtrio;
import com.jeff.pets.cobblepets.pets.gen1.ditto.Ditto;
import com.jeff.pets.cobblepets.pets.gen1.doduo.Dodrio;
import com.jeff.pets.cobblepets.pets.gen1.doduo.Doduo;
import com.jeff.pets.cobblepets.pets.gen1.drowzee.Drowzee;
import com.jeff.pets.cobblepets.pets.gen1.drowzee.Hypno;
import com.jeff.pets.cobblepets.pets.gen1.ekans.Arbok;
import com.jeff.pets.cobblepets.pets.gen1.ekans.Ekans;
import com.jeff.pets.cobblepets.pets.gen1.exeggcute.Exeggcute;
import com.jeff.pets.cobblepets.pets.gen1.exeggcute.Exeggutor;
import com.jeff.pets.cobblepets.pets.gen1.farfetchd.Farfetchd;
import com.jeff.pets.cobblepets.pets.gen1.gastly.Gastly;
import com.jeff.pets.cobblepets.pets.gen1.gastly.Gengar;
import com.jeff.pets.cobblepets.pets.gen1.gastly.Haunter;
import com.jeff.pets.cobblepets.pets.gen1.geodude.Geodude;
import com.jeff.pets.cobblepets.pets.gen1.geodude.Golem;
import com.jeff.pets.cobblepets.pets.gen1.geodude.Graveler;
import com.jeff.pets.cobblepets.pets.gen1.grimer.Grimer;
import com.jeff.pets.cobblepets.pets.gen1.grimer.Muk;
import com.jeff.pets.cobblepets.pets.gen1.growlith.Arcanine;
import com.jeff.pets.cobblepets.pets.gen1.growlith.Growlith;
import com.jeff.pets.cobblepets.pets.gen1.jigglypuff.Jigglypuff;
import com.jeff.pets.cobblepets.pets.gen1.jigglypuff.Wigglytuff;
import com.jeff.pets.cobblepets.pets.gen1.krabby.Kingler;
import com.jeff.pets.cobblepets.pets.gen1.krabby.Krabby;
import com.jeff.pets.cobblepets.pets.gen1.machop.Machamp;
import com.jeff.pets.cobblepets.pets.gen1.machop.Machoke;
import com.jeff.pets.cobblepets.pets.gen1.machop.Machop;
import com.jeff.pets.cobblepets.pets.gen1.magnamite.Magnemite;
import com.jeff.pets.cobblepets.pets.gen1.magnamite.Magneton;
import com.jeff.pets.cobblepets.pets.gen1.mankey.Mankey;
import com.jeff.pets.cobblepets.pets.gen1.mankey.Primeape;
import com.jeff.pets.cobblepets.pets.gen1.meowth.Meowth;
import com.jeff.pets.cobblepets.pets.gen1.meowth.Persian;
import com.jeff.pets.cobblepets.pets.gen1.mew.Mew;
import com.jeff.pets.cobblepets.pets.gen1.mew.Mewtwo;
import com.jeff.pets.cobblepets.pets.gen1.nidoramf.Nidoqueen;
import com.jeff.pets.cobblepets.pets.gen1.nidoramf.Nidoranf;
import com.jeff.pets.cobblepets.pets.gen1.nidoramf.Nidorina;
import com.jeff.pets.cobblepets.pets.gen1.nidoranm.Nidoking;
import com.jeff.pets.cobblepets.pets.gen1.nidoranm.Nidoranm;
import com.jeff.pets.cobblepets.pets.gen1.nidoranm.Nidorino;
import com.jeff.pets.cobblepets.pets.gen1.oddish.Gloom;
import com.jeff.pets.cobblepets.pets.gen1.oddish.Oddish;
import com.jeff.pets.cobblepets.pets.gen1.oddish.Vileplume;
import com.jeff.pets.cobblepets.pets.gen1.onix.Onix;
import com.jeff.pets.cobblepets.pets.gen1.paras.Paras;
import com.jeff.pets.cobblepets.pets.gen1.paras.Parasect;
import com.jeff.pets.cobblepets.pets.gen1.pidgey.Pidgeot;
import com.jeff.pets.cobblepets.pets.gen1.pidgey.Pidgeotto;
import com.jeff.pets.cobblepets.pets.gen1.pidgey.Pidgey;
import com.jeff.pets.cobblepets.pets.gen1.pikachu.Pikachu;
import com.jeff.pets.cobblepets.pets.gen1.pikachu.Raichu;
import com.jeff.pets.cobblepets.pets.gen1.poliwag.Poliwag;
import com.jeff.pets.cobblepets.pets.gen1.poliwag.Poliwhirl;
import com.jeff.pets.cobblepets.pets.gen1.poliwag.Poliwrath;
import com.jeff.pets.cobblepets.pets.gen1.ponyta.Ponyta;
import com.jeff.pets.cobblepets.pets.gen1.ponyta.Rapidash;
import com.jeff.pets.cobblepets.pets.gen1.psyduck.Golduck;
import com.jeff.pets.cobblepets.pets.gen1.psyduck.Psyduck;
import com.jeff.pets.cobblepets.pets.gen1.rattata.Raticate;
import com.jeff.pets.cobblepets.pets.gen1.rattata.Rattata;
import com.jeff.pets.cobblepets.pets.gen1.sandshrew.Sandshrew;
import com.jeff.pets.cobblepets.pets.gen1.sandshrew.Sandslash;
import com.jeff.pets.cobblepets.pets.gen1.seel.Dewgong;
import com.jeff.pets.cobblepets.pets.gen1.seel.Seel;
import com.jeff.pets.cobblepets.pets.gen1.shellder.Cloyster;
import com.jeff.pets.cobblepets.pets.gen1.shellder.Shellder;
import com.jeff.pets.cobblepets.pets.gen1.slowpoke.Slowbro;
import com.jeff.pets.cobblepets.pets.gen1.slowpoke.Slowpoke;
import com.jeff.pets.cobblepets.pets.gen1.spearow.Fearow;
import com.jeff.pets.cobblepets.pets.gen1.spearow.Spearow;
import com.jeff.pets.cobblepets.pets.gen1.squirtle.Blastoise;
import com.jeff.pets.cobblepets.pets.gen1.squirtle.Squirtle;
import com.jeff.pets.cobblepets.pets.gen1.squirtle.Wartortle;
import com.jeff.pets.cobblepets.pets.gen1.tentacool.Tentacool;
import com.jeff.pets.cobblepets.pets.gen1.tentacool.Tentacruel;
import com.jeff.pets.cobblepets.pets.gen1.venonat.Venomoth;
import com.jeff.pets.cobblepets.pets.gen1.venonat.Venonat;
import com.jeff.pets.cobblepets.pets.gen1.voltorb.Electrode;
import com.jeff.pets.cobblepets.pets.gen1.voltorb.Voltorb;
import com.jeff.pets.cobblepets.pets.gen1.vulpix.Ninetales;
import com.jeff.pets.cobblepets.pets.gen1.vulpix.Vulpix;
import com.jeff.pets.cobblepets.pets.gen1.weedle.Beedrill;
import com.jeff.pets.cobblepets.pets.gen1.weedle.Kakuna;
import com.jeff.pets.cobblepets.pets.gen1.weedle.Weedle;
import com.jeff.pets.cobblepets.pets.gen1.zubat.Golbat;
import com.jeff.pets.cobblepets.pets.gen1.zubat.Zubat;
import com.jeff.pets.cobblepets.pets.gen4.riolu.Lucario;
import com.jeff.pets.cobblepets.pets.gen4.riolu.Riolu;
import com.jeff.pets.cobblepets.pets.gen5.snivy.Serperior;
import com.jeff.pets.cobblepets.pets.gen5.snivy.Servine;
import com.jeff.pets.cobblepets.pets.gen5.snivy.Snivy;
import com.jeff.pets.mob.AbstractPet;
import com.llamalad7.mixinextras.injector.ModifyReturnValue;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import static com.jeff.pets.client.Central.CONFIG;
import static com.jeff.pets.cobblepets.client.CobblepetsClient.COBBLE_CONFIG;
import static com.jeff.pets.cobblepets.client.Vals.*;

@Mixin(Utils.class)
public class UtilMixin {
    @Inject(at = @At("HEAD"), method = "setActivePetName")
    private static void cobblepets$setActivePetName(String name, CallbackInfo ci) {
        com.jeff.pets.cobblepets.client.Utils.assignName(name);
    }

    @ModifyReturnValue(at = @At("RETURN"), method = "getActivePetName")
    private static String cobblepets$getActivePetName(String original) {
        return switch (CONFIG.activePet) {
            case BULBASAUR -> COBBLE_CONFIG.bulbasorName;
            case IVYSAUR -> COBBLE_CONFIG.ivysaurName;
            case VENUSAUR -> COBBLE_CONFIG.venusaurName;
            case CHARMANDER -> COBBLE_CONFIG.charmanderName;
            case CHARMELEON -> COBBLE_CONFIG.charmeleonName;
            case CHARIZARD -> COBBLE_CONFIG.charizardName;
            case SQUIRTLE -> COBBLE_CONFIG.squirtleName;
            case BLASTOISE -> COBBLE_CONFIG.blastoiseName;
            case WARTORTLE -> COBBLE_CONFIG.wartortleName;
            case CATERPIE -> COBBLE_CONFIG.caterpieName;
            case METAPOD -> COBBLE_CONFIG.metapodName;
            case BUTTERFREE -> COBBLE_CONFIG.butterfreeName;
            case WEEDLE -> COBBLE_CONFIG.weedleName;
            case KAKUNA -> COBBLE_CONFIG.kakunaName;
            case BEEDRILL -> COBBLE_CONFIG.beedrillName;
            case PIDGEY -> COBBLE_CONFIG.pidgeyName;
            case PIDGEOTTO -> COBBLE_CONFIG.pidgeottoName;
            case PIDGEOT -> COBBLE_CONFIG.pidgeotName;
            case MEW -> COBBLE_CONFIG.mewName;
            case MEWTWO -> COBBLE_CONFIG.mewtwoName;
            case DITTO -> COBBLE_CONFIG.dittoName;
            case RATTATA -> COBBLE_CONFIG.rattataName;
            case RATICATE -> COBBLE_CONFIG.raticateName;
            case SPEAROW -> COBBLE_CONFIG.spearowName;
            case FEAROW -> COBBLE_CONFIG.fearowName;
            case EKANS -> COBBLE_CONFIG.ekansName;
            case ARBOK -> COBBLE_CONFIG.arbokName;
            case PIKACHU -> COBBLE_CONFIG.pikachuName;
            case RAICHU -> COBBLE_CONFIG.raichuName;
            case SANDSHREW -> COBBLE_CONFIG.sandshrewName;
            case SANDSLASH -> COBBLE_CONFIG.sandslashName;
            case NIDORANF -> COBBLE_CONFIG.nidoranfName;
            case NIDORINA -> COBBLE_CONFIG.nidorinaName;
            case NIDOQUEEN -> COBBLE_CONFIG.nidoqueenName;
            case NIDORANM -> COBBLE_CONFIG.nidoranmName;
            case NIDORINO -> COBBLE_CONFIG.nidorinoName;
            case NIDOKING -> COBBLE_CONFIG.nidokingName;
            case CLEFAIRY -> COBBLE_CONFIG.clefairyName;
            case CLEFABLE -> COBBLE_CONFIG.clefableName;
            case VULPIX -> COBBLE_CONFIG.vulpixName;
            case NINETALES -> COBBLE_CONFIG.ninetalesName;
            case JIGGLYPUFF -> COBBLE_CONFIG.jigglypuffName;
            case WIGGLYTUFF -> COBBLE_CONFIG.wigglytuffName;
            case ZUBAT -> COBBLE_CONFIG.zubatName;
            case GOLBAT -> COBBLE_CONFIG.golbatName;
            case ODDISH -> COBBLE_CONFIG.oddishName;
            case GLOOM -> COBBLE_CONFIG.gloomName;
            case VILEPLUME -> COBBLE_CONFIG.vileplumeName;
            case PARAS -> COBBLE_CONFIG.parasName;
            case PARASECT -> COBBLE_CONFIG.parasectName;
            case VENONAT -> COBBLE_CONFIG.venonatName;
            case VENOMOTH -> COBBLE_CONFIG.venomothName;
            case DIGLETT -> COBBLE_CONFIG.diglettName;
            case DUGTRIO -> COBBLE_CONFIG.dugtrioName;
            case MEOWTH -> COBBLE_CONFIG.meowthName;
            case PERSIAN -> COBBLE_CONFIG.persianName;
            case PSYDUCK -> COBBLE_CONFIG.psyduckName;
            case GOLDUCK -> COBBLE_CONFIG.golduckName;
            case MANKEY -> COBBLE_CONFIG.mankeyName;
            case PRIMEAPE -> COBBLE_CONFIG.primeapeName;
            case GROWLITHE -> COBBLE_CONFIG.growlithName;
            case ARCANINE -> COBBLE_CONFIG.arcanineName;
            case POLIWAG -> COBBLE_CONFIG.poliwagName;
            case POLIWHIRL -> COBBLE_CONFIG.poliwhirlName;
            case POLIWRATH -> COBBLE_CONFIG.poliwrathName;
            case ABRA -> COBBLE_CONFIG.abraName;
            case KADABRA -> COBBLE_CONFIG.kadabraName;
            case ALAKAZAM -> COBBLE_CONFIG.alakazamName;
            case MACHOP -> COBBLE_CONFIG.machopName;
            case MACHOKE -> COBBLE_CONFIG.machokeName;
            case MACHAMP -> COBBLE_CONFIG.machampName;
            case BELLSPROUT -> COBBLE_CONFIG.bellsproutName;
            case WEEPINBELL -> COBBLE_CONFIG.weepinbellName;
            case VICTREEBEL -> COBBLE_CONFIG.victreebelName;
            case TENTACOOL -> COBBLE_CONFIG.tentacoolName;
            case TENTACRUEL -> COBBLE_CONFIG.tentacruelName;
            case GEODUDE -> COBBLE_CONFIG.geodudeName;
            case GRAVELER -> COBBLE_CONFIG.gravelerName;
            case GOLEM -> COBBLE_CONFIG.golemName;
            case PONYTA -> COBBLE_CONFIG.ponytaName;
            case RAPIDASH -> COBBLE_CONFIG.rapidashName;
            case SLOWPOKE -> COBBLE_CONFIG.slowpokeName;
            case SLOWBRO -> COBBLE_CONFIG.slowbroName;
            case MAGNEMITE -> COBBLE_CONFIG.magnemiteName;
            case MAGNETON -> COBBLE_CONFIG.magnetonName;
            case FARFETCHD -> COBBLE_CONFIG.farfetchdName;
            case DODUO -> COBBLE_CONFIG.doduoName;
            case DODRIO -> COBBLE_CONFIG.dodrioName;
            case SEEL -> COBBLE_CONFIG.seelName;
            case DEWGONG -> COBBLE_CONFIG.dewgongName;
            case GRIMER -> COBBLE_CONFIG.grimerName;
            case MUK -> COBBLE_CONFIG.mukName;
            case SHELLDER -> COBBLE_CONFIG.shellderName;
            case CLOYSTER -> COBBLE_CONFIG.cloysterName;
            case GASTLY -> COBBLE_CONFIG.gastlyName;
            case HAUNTER -> COBBLE_CONFIG.haunterName;
            case GENGAR -> COBBLE_CONFIG.gengarName;
            case ONIX -> COBBLE_CONFIG.onixName;
            case DROWZEE -> COBBLE_CONFIG.drowzeeName;
            case HYPNO -> COBBLE_CONFIG.hypnoName;
            case KRABBY -> COBBLE_CONFIG.krabbyName;
            case KINGLER -> COBBLE_CONFIG.kinglerName;
            case VOLTORB -> COBBLE_CONFIG.voltorbName;
            case ELECTRODE -> COBBLE_CONFIG.electrodeName;
            case EXEGGCUTE -> COBBLE_CONFIG.exeggcuteName;
            case EXEGGUTOR -> COBBLE_CONFIG.exeggutorName;
            case RIOLU -> COBBLE_CONFIG.rioluName;
            case LUCARIO -> COBBLE_CONFIG.lucarioName;
            case SNIVY -> COBBLE_CONFIG.snivyName;
            case SERVINE -> COBBLE_CONFIG.servineName;
            case SERPERIOR -> COBBLE_CONFIG.serperiorName;
            case CUBONE -> COBBLE_CONFIG.cuboneName;
            case MAROWAK -> COBBLE_CONFIG.marowakName;

            case null, default -> original;
        };
    }

    @ModifyReturnValue(at = @At("RETURN"), method = "getPet")
    private static AbstractPet cobblepets$getPet(AbstractPet original) {
        ClientLevel level = Minecraft.getInstance().level;
        return switch (CONFIG.activePet) {
            case BULBASAUR -> new Bulbasaur(Cobblepets.BULBASAUR, level);
            case IVYSAUR -> new Ivysaur(Cobblepets.IVYSAUR, level);
            case VENUSAUR -> new Venusaur(Cobblepets.VENUSAUR, level);
            case CHARMANDER -> new Charmander(Cobblepets.CHARMANDER, level);
            case CHARMELEON -> new Charmeleon(Cobblepets.CHARMELEON, level);
            case CHARIZARD -> new Charizard(Cobblepets.CHARIZARD, level);
            case SQUIRTLE -> new Squirtle(Cobblepets.SQUIRTLE, level);
            case WARTORTLE -> new Wartortle(Cobblepets.WARTORTLE, level);
            case BLASTOISE -> new Blastoise(Cobblepets.BLASTOISE, level);
            case CATERPIE -> new com.jeff.pets.cobblepets.pets.gen1.bulbasaur.caterpie.Caterpie(Cobblepets.CATERPIE, level);
            case METAPOD -> new com.jeff.pets.cobblepets.pets.gen1.bulbasaur.caterpie.Metapod(Cobblepets.METAPOD, level);
            case BUTTERFREE -> new com.jeff.pets.cobblepets.pets.gen1.bulbasaur.caterpie.Butterfree(Cobblepets.BUTTERFREE, level);
            case WEEDLE -> new Weedle(Cobblepets.WEEDLE, level);
            case KAKUNA -> new Kakuna(Cobblepets.KAKUNA, level);
            case BEEDRILL -> new Beedrill(Cobblepets.BEEDRILL, level);
            case PIDGEY -> new Pidgey(Cobblepets.PIDGEY, level);
            case PIDGEOTTO -> new Pidgeotto(Cobblepets.PIDGEOTTO, level);
            case PIDGEOT -> new Pidgeot(Cobblepets.PIDGEOT, level);
            case MEW -> new Mew(Cobblepets.MEW, level);
            case MEWTWO -> new Mewtwo(Cobblepets.MEWTWO, level);
            case DITTO -> new Ditto(Cobblepets.DITTO, level);
            case RATTATA -> new Rattata(Cobblepets.RATTATA, level);
            case RATICATE -> new Raticate(Cobblepets.RATICATE, level);
            case SPEAROW -> new Spearow(Cobblepets.SPEAROW, level);
            case FEAROW -> new Fearow(Cobblepets.FEAROW, level);
            case EKANS -> new Ekans(Cobblepets.EKANS, level);
            case ARBOK -> new Arbok(Cobblepets.ARBOK, level);
            case PIKACHU -> new Pikachu(Cobblepets.PIKACHU, level);
            case RAICHU -> new Raichu(Cobblepets.RAICHU, level);
            case SANDSHREW -> new Sandshrew(Cobblepets.SANDSHREW, level);
            case SANDSLASH -> new Sandslash(Cobblepets.SANDSLASH, level);
            case NIDORANF -> new Nidoranf(Cobblepets.NIDORANF, level);
            case NIDORINA -> new Nidorina(Cobblepets.NIDORINA, level);
            case NIDOQUEEN -> new Nidoqueen(Cobblepets.NIDOQUEEN, level);
            case NIDORANM -> new Nidoranm(Cobblepets.NIDORANM, level);
            case NIDORINO -> new Nidorino(Cobblepets.NIDORINO, level);
            case NIDOKING -> new Nidoking(Cobblepets.NIDOKING, level);
            case CLEFAIRY -> new Clefairy(Cobblepets.CLEFAIRY, level);
            case CLEFABLE -> new Clefable(Cobblepets.CLEFABLE, level);
            case VULPIX -> new Vulpix(Cobblepets.VULPIX, level);
            case NINETALES -> new Ninetales(Cobblepets.NINETALES, level);
            case JIGGLYPUFF -> new Jigglypuff(Cobblepets.JIGGLYPUFF, level);
            case WIGGLYTUFF -> new Wigglytuff(Cobblepets.WIGGLYTUFF, level);
            case ZUBAT -> new Zubat(Cobblepets.ZUBAT, level);
            case GOLBAT -> new Golbat(Cobblepets.GOLBAT, level);
            case ODDISH -> new Oddish(Cobblepets.ODDISH, level);
            case GLOOM -> new Gloom(Cobblepets.GLOOM, level);
            case VILEPLUME -> new Vileplume(Cobblepets.VILEPLUME, level);
            case PARAS -> new Paras(Cobblepets.PARAS, level);
            case PARASECT -> new Parasect(Cobblepets.PARASECT, level);
            case VENONAT -> new Venonat(Cobblepets.VENONAT, level);
            case VENOMOTH -> new Venomoth(Cobblepets.VENOMOTH, level);
            case DIGLETT -> new Diglett(Cobblepets.DIGLETT, level);
            case DUGTRIO -> new Dugtrio(Cobblepets.DUGTRIO, level);
            case MEOWTH -> new Meowth(Cobblepets.MEOWTH, level);
            case PERSIAN -> new Persian(Cobblepets.PERSIAN, level);
            case PSYDUCK -> new Psyduck(Cobblepets.PSYDUCK, level);
            case GOLDUCK -> new Golduck(Cobblepets.GOLDUCK, level);
            case MANKEY -> new Mankey(Cobblepets.MANKEY, level);
            case PRIMEAPE -> new Primeape(Cobblepets.PRIMEAPE, level);
            case GROWLITHE -> new Growlith(Cobblepets.GROWLITHE, level);
            case ARCANINE -> new Arcanine(Cobblepets.ARCANINE, level);
            case POLIWAG -> new Poliwag(Cobblepets.POLIWAG, level);
            case POLIWHIRL -> new Poliwhirl(Cobblepets.POLIWHIRL, level);
            case POLIWRATH -> new Poliwrath(Cobblepets.POLIWRATH, level);
            case ABRA -> new Abra(Cobblepets.ABRA, level);
            case KADABRA -> new Kadabra(Cobblepets.KADABRA, level);
            case ALAKAZAM -> new Alakazam(Cobblepets.ALAKAZAM, level);
            case MACHOP -> new Machop(Cobblepets.MACHOP, level);
            case MACHOKE -> new Machoke(Cobblepets.MACHOKE, level);
            case MACHAMP -> new Machamp(Cobblepets.MACHAMP, level);
            case BELLSPROUT -> new Bellsprout(Cobblepets.BELLSPROUT, level);
            case WEEPINBELL -> new Weepinbell(Cobblepets.WEEPINBELL, level);
            case VICTREEBEL -> new Victreebel(Cobblepets.VICTREEBEL, level);
            case TENTACOOL -> new Tentacool(Cobblepets.TENTACOOL, level);
            case TENTACRUEL -> new Tentacruel(Cobblepets.TENTACRUEL, level);
            case GEODUDE -> new Geodude(Cobblepets.GEODUDE, level);
            case GRAVELER -> new Graveler(Cobblepets.GRAVELER, level);
            case GOLEM -> new Golem(Cobblepets.GOLEM, level);
            case PONYTA -> new Ponyta(Cobblepets.PONYTA, level);
            case RAPIDASH -> new Rapidash(Cobblepets.RAPIDASH, level);
            case SLOWBRO -> new Slowbro(Cobblepets.SLOWBRO, level);
            case SLOWPOKE -> new Slowpoke(Cobblepets.SLOWPOKE, level);
            case MAGNETON -> new Magneton(Cobblepets.MAGNETON, level);
            case MAGNEMITE -> new Magnemite(Cobblepets.MAGNEMITE, level);
            case FARFETCHD -> new Farfetchd(Cobblepets.FARFETCHD, level);
            case DODUO -> new Doduo(Cobblepets.DODUO, level);
            case DODRIO -> new Dodrio(Cobblepets.DODRIO, level);
            case SEEL -> new Seel(Cobblepets.SEEL, level);
            case DEWGONG -> new Dewgong(Cobblepets.DEWGONG, level);
            case GRIMER -> new Grimer(Cobblepets.GRIMER, level);
            case MUK -> new Muk(Cobblepets.MUK, level);
            case SHELLDER -> new Shellder(Cobblepets.SHELLDER, level);
            case CLOYSTER -> new Cloyster(Cobblepets.CLOYSTER, level);
            case GASTLY -> new Gastly(Cobblepets.GASTLY, level);
            case HAUNTER -> new Haunter(Cobblepets.HAUNTER, level);
            case GENGAR -> new Gengar(Cobblepets.GENGAR, level);
            case ONIX -> new Onix(Cobblepets.ONIX, level);
            case DROWZEE -> new Drowzee(Cobblepets.DROWZEE, level);
            case HYPNO -> new Hypno(Cobblepets.HYPNO, level);
            case KRABBY -> new Krabby(Cobblepets.KRABBY, level);
            case KINGLER -> new Kingler(Cobblepets.KINGLER, level);
            case VOLTORB -> new Voltorb(Cobblepets.VOLTORB, level);
            case ELECTRODE -> new Electrode(Cobblepets.ELECTRODE, level);
            case EXEGGCUTE -> new Exeggcute(Cobblepets.EXEGGCUTE, level);
            case EXEGGUTOR -> new Exeggutor(Cobblepets.EXEGGUTOR, level);
            case CUBONE -> new Cubone(Cobblepets.CUBONE, level);
            case MAROWAK -> new Marowak(Cobblepets.MAROWAK, level);
            case RIOLU -> new Riolu(Cobblepets.RIOLU, level);
            case LUCARIO -> new Lucario(Cobblepets.LUCARIO, level);
            case SNIVY -> new Snivy(Cobblepets.SNIVY, level);
            case SERVINE -> new Servine(Cobblepets.SERVINE, level);
            case SERPERIOR -> new Serperior(Cobblepets.SERPERIOR, level);
            default -> original;
        };
    }
}
